@startuml Camera Calibration
<style>
element{ HorizontalAlignment:center; }
</style>
start
:Get\nGain\nList;
:Get\nExposure\nList;
:Get Brightness;
while (Calibrated) is (no)
    while (Light in Lights-List) is (yes)
        :Set Light;
        while (Color in Colors-List) is (yes)
            :Set Color;
            while (Gain in Gain-List) is (yes)
                :Set\namera\nGain;
                while (Exposure in Exposure-List) is (yes)
                    :Set\ncamera\nExposure;
                    while (Brightness in Brightness-List) is (yes)
                        :Set\ncamera\nBrightness;
                        :Create\nSettings array\nwith\nGain, Exposure and Brightness;
                        :Get picture;
                        :Compute gradient;
                        :Add\nSettings array and gradient\nto array;
                    endwhile (no)
                endwhile (no)
            endwhile (no)
        endwhile (no)
    endwhile (no)
endwhile (yes)
:Find\nsettings\nwith\nhighest gradient;
:Save those settings;
stop
@enduml