@startuml Camera Calibration
start
:Get Gain List;
:Get Exposure List;
:Get Brightness;
while (Calibrated) is (no)
    while (Light in Lights-List)
        :Set Light;
        while (Color in Colors-List)
            :Set Color;
            while (Gain in Gain-List)
                :Set camera Gain;
                while (Exposure in Exposure-List)
                    :Set camera Exposure;
                    while (Brightness in Brightness-List)
                        :Set camera Brightness;
                        :Create Settings-array with Gain, Exposure and Brightness;
                        :Get picture;
                        :Compute gradient;
                        :Add Settings-array and gradient to array;
                    endwhile (no)
                endwhile (no)
            endwhile (no)
        endwhile (no)
    endwhile (no)
endwhile (yes)
:Find settings with highest gradient;
:Save those settings;
stop
@enduml