@startuml Camera Main Loop
<style>
element{ HorizontalAlignment:center; }
</style>
start
while (Stop request received) is (no)
    if (Take Picture event received) then (yes)
        :Take picture;
        :Send\npicture\nthru picture event\nto requiring module;
    endif
endwhile (received)
stop
@enduml