@startuml Camera Calibration
start
:Get ISO List;
:Get Exposure List;
:Get Brightness;
while (Calibrated) is (no)
    while (ISO in ISO-List)
        :Set camera ISO;
        while (Exposure in Exposure-List)
            :Set camera Exposure;
            while (Brightness in Brightness-List)
                :Set camera Brightness;
                :Create Settings-array with ISO, Exposure and Brightness;
                :Get picture;
                :Compute gradient;
                :Add Settings-array and gradient to array;
            endwhile (no)
        endwhile (no)
    endwhile (no)
endwhile (yes)
:Find settings with highest gradient;
:Save those settings;
stop
@enduml