@startuml Spectrometer activity flow
start
while (stop signal?) is (no)
    if (Cuvette present?) then (yes)
        :Start camera;
        :Get picture;
        :Get spectrograph;
        :Analyze spectrograph;
        :Return spectrograph and solution composition;
        while (cuvette present?) is (yes)
            :Waiting for cuvette release;
        endwhile (no)
    endif
endwhile (yes)
stop
@enduml