@startuml Boot activity
start
:Load configuration;
:Set the camera;
:Calibrate the camera;
:Set the light;
:Calibrate the light;
if (Is the first boot ever?) then (yes)
    :Get the spectrographs database;
else (no)
    if (New spectrographs\nor\nspectrographs updates?) then (yes)
        :Get updates;
    else (no)
    endif
endif
:Calibrate Cuvette Presence Sequence;
stop
@enduml