name: Python Integration Tests

on:
  workflow_run:
    workflows: ["Python Unit Tests"]
    types:
      - completed
    branches:
      - master
      - refactor
jobs:
  build:
    runs-on: self-hosted
    if: github.event.workflow_run.conclusion == 'success'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcap-dev libcamera-dev
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r antlampas/raspiscope-python/raspiscope-python-refactor/requirements.txt
    - name: Run Integration Tests
      run: |
        python -m unittest antlampas/raspiscope-python/raspiscope-python-refactor/tests/test_integration.py