name: Python Integration Tests

on:
  push:
    branches: [ refactor ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcap-dev
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Unit Tests
      run: |
        python -m unittest discover tests/integration