name: Python Unit Tests

on:
  push:
    branches: [ refactor ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # Installa le dipendenze dal file requirements.txt
        # Nota: L'installazione di librerie hardware come rpi_ws281x o gpiozero
        # potrebbe fallire su un runner standard. Poiché i tuoi test
        # utilizzano i mock, puoi commentarle nel file requirements.txt
        # se l'installazione fallisce, per eseguire comunque i test.
        pip install -r antlampas/raspiscope-python/raspiscope-python-refactor/requirements.txt

    - name: Run Unit Tests
      run: |
        # Esegue i test scoprendo tutti i file che iniziano con 'test'
        # nella cartella 'tests' e nelle sottocartelle
        python -m unittest discover antlampas/raspiscope-python/raspiscope-python-refactor/tests