name: Python Unit Tests

on:
  push:
    branches: [ refactor ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcap-dev libcamera-dev
    - name: Create virtual environment
      run: |
        python -m venv "${{ github.event.repository.name }}"
        cd ${{ github.event.repository.name }}
        source bin/activate
        bin/python -m pip install --upgrade pip
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        path: .
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Run Unit Tests
      run: |
        bin/python -m unittest discover tests/unit