name: Python Unit Tests

on:
  push:
    branches: [ refactor ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcap-dev libcamera-dev
    - name: Create virtual environment
      run: |
        python -m venv "${{ github.event.repository.name }}"
        source ${{ github.event.repository.name }}/bin/activate
        ${{ github.event.repository.name }}/bin/python -m pip install --upgrade pip
        pip install -r ${{ github.event.repository.name }}/requirements.txt
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        path: .
    - name: Run Unit Tests
      run: |
        ${{ github.event.repository.name }}/bin/python -m unittest discover tests/unit