name: Python Unit Tests
on:
  push:
    branches: [ refactor ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcap-dev libcamera-dev
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Install Dependencies and Run Tests
      run: |
        python3 -m venv .venv
        cd .venv
        source bin/activate
        bin/python -m pip install --upgrade pip
        bin/python -m pip install pur
        bin/python -m pip install -r requirements.txt
        pur -r requirements.txt
        echo "Avvio i test..."
        bin/python -m unittest discover tests/unit