name: Python Unit Tests
on:
  workflow_dispatch:
  pull_request:
    branches: [ tests ]
jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcap-dev libcamera-dev
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Install Dependencies and Run Tests
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        .venv/bin/python -m pip install --upgrade pip
        .venv/bin/python -m pip install -r requirements.txt
        echo "Avvio i test..."
        .venv/bin/python -m unittest discover tests/unit