name: Python Unit Tests
on:
  workflow_dispatch:
  pull_request:
    branches: [ tests ]
jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
    - name: Install System Dependencies
      run: |
        echo "Installing system dependencies"
        sudo apt-get update
        sudo apt-get install -y python3-picamera2 libcap-dev libcamera-dev
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Install Dependencies and Run Tests
      run: |
        echo "Upgrading pip..."
        python -m pip install --upgrade pip
        echo "Installing requirements..."
        python -m pip install -r requirements.txt
        echo "Starting tests..."
        python -m unittest discover tests/unit